In [ ]:
z

KeyboardInterrupt: ignored

In [ ]:
#Here i am importing some necessary packages liberaries
import pandas as pd
import seaborn as sns
import datetime as dt
import numpy as np

#Dataset Exploration

In [4]:
#Here i am accessing the dataset file which covid.csv from my google drive
dataR2 = pd.read_csv('gdrive/MyDrive/BreastCancerDetection/dataR2.csv')

NameError: ignored

In [3]:
#Here I am showing only top 5 rows of our dataset
dataset.head()

NameError: ignored

In [ ]:
#Looking at the shape
dataset.shape

(116, 10)

In [ ]:
#Looking at columns
dataset.columns

Index(['Age', 'BMI', 'Glucose', 'Insulin', 'HOMA', 'Leptin', 'Adiponectin',
       'Resistin', 'MCP.1', 'Classification'],
      dtype='object')

In [ ]:
#Checking if columns have null values
dataset.isna().any()

Age               False
BMI               False
Glucose           False
Insulin           False
HOMA              False
Leptin            False
Adiponectin       False
Resistin          False
MCP.1             False
Classification    False
dtype: bool

In [ ]:
#Getting the sum of null values across each column
dataset.isna().sum()

Age               0
BMI               0
Glucose           0
Insulin           0
HOMA              0
Leptin            0
Adiponectin       0
Resistin          0
MCP.1             0
Classification    0
dtype: int64

# Preparing dataset

In [ ]:
#Getting the columns which will be used for features
X = dataset[['Age', 'BMI', 'Glucose', 'Insulin', 'HOMA', 'Leptin', 'Adiponectin', 'Resistin', 'MCP.1']]
#Getting the column which will be used as predictor
y = covid["Classification"]

In [ ]:
# I am getting the train_test_split function for splitting my dateset into training and testing
from sklearn.model_selection import train_test_split

In [ ]:
# I am splitting the dataset
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.05)

#Training Models

## Model 1: Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
logmodel = LogisticRegression(solver='lbfgs', max_iter=4000)

In [ ]:
logmodel.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=4000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_pred = logmodel.predict(x_test)

In [ ]:
y_pred

array([2, 1, 1, 2, 1, 1])

In [ ]:
print("Accuracy: %d", (logmodel.score(x_test, y_test)))

Accuracy: %d 0.5


In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix = confusion_matrix(y_test, y_pred)

In [ ]:
print(confusion_matrix)

[[3 2]
 [1 0]]


## Model2: Decision Tree

In [ ]:

# import the Decision Tree classifier
from sklearn.tree import DecisionTreeClassifier

In [ ]:
# create a regressor object
dtClassifier = DecisionTreeClassifier(random_state = 0) 

In [ ]:
# fit the regressor with X and Y data
dtClassifier.fit(X, y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [ ]:
yPred = dtClassifier.predict(x_test)

In [ ]:
yPred

array([1, 1, 2, 1, 1, 1])

In [ ]:
print("Accuracy: %d", (dtClassifier.score(x_test, y_test)))

Accuracy: %d 1.0


In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix = confusion_matrix(y_test, yPred)

In [ ]:
print(confusion_matrix)

[[5 0]
 [0 1]]
